version: '3.6'
services:
  hub:
    build:
      context: packages/hub
    ports:
      - 3000:3000
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
