#!/usr/bin/env bash

echo "
DEBUG=false

API_URL=${API_URL}
ENDPOINT_URL=${ENDPOINT_URL}
JWT_SECRET=${JWT_SECRET}
REDIRECT_URL=${REDIRECT_URL}
SERVER_ID=${SERVER_ID}

SMARTTHINGS_CLIENT_ID=${SMARTTHINGS_CLIENT_ID}
SMARTTHINGS_CLIENT_SECRET=${SMARTTHINGS_CLIENT_SECRET}
SMARTTHINGS_TOKEN_HOST=${SMARTTHINGS_TOKEN_HOST}
" > .env
